### ISSUE TITLE
Struggling to get device ID and local ID

### ISSUE THREAD

**Issue by treforparr** [joshstrange/eufy-robovac#7]
Anyway you could do this in the terminal command like

**Comment by apexad** [comment]
Use https://www.bluestacks.com
with
https://www.apkmirror.com/apk/anker/eufyhome/eufyhome-2-3-2-release/eufyhome-2-3-2-android-apk-download/

Otherwise instructions are here:
https://github.com/joshstrange/eufy-robovac/blob/master/README.md
I am investigating better ways to get deviceId and localKey, possibly by just using your username/password but I have no ETA on that.
